"""Added role column

Revision ID: b2e10416588b
Revises: 9d1de74edeed
Create Date: 2025-04-30 16:05:06.747100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2e10416588b'
down_revision = '9d1de74edeed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=False))
        batch_op.alter_column('updated',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # Update role column for existing records
    op.execute("UPDATE user_account SET role = 2 WHERE alias IS NOT NULL AND alias != 'User'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.alter_column('updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('role')

    # ### end Alembic commands ###
